{u'billing_address': {u'address_1': u'Jogeshvari',
  u'address_2': u'',
  u'city': u'Mumbai',
  u'company': u'Globalteckz',
  u'country': u'IN',
  u'email': u'jinal@globalteckz.com',
  u'first_name': u'Jinal',
  u'last_name': u'Patel',
  u'phone': u'567868798789',
  u'postcode': u'400068',
  u'state': u'MH'},
 u'cart_tax': u'0.00',
 u'completed_at': u'1970-01-01T00:00:00Z',
 u'coupon_lines': [],
 u'created_at': u'2017-05-05T13:27:00Z',
 u'currency': u'USD',
 u'customer': {u'avatar_url': u'http://0.gravatar.com/avatar/333ad346baa8129298a1f57d5264e0bc?s=96',
  u'billing_address': {u'address_1': u'Jogeshvari',
   u'address_2': u'',
   u'city': u'Mumbai',
   u'company': u'Globalteckz',
   u'country': u'IN',
   u'email': u'jinal@globalteckz.com',
   u'first_name': u'Jinal',
   u'last_name': u'Patel',
   u'phone': u'567868798789',
   u'postcode': u'400068',
   u'state': u'MH'},
  u'created_at': u'2017-04-20T11:00:23Z',
  u'email': u'admin@woocomm.globalteckz.com',
  u'first_name': u'Jinal',
  u'id': 1,
  u'last_name': u'Patel',
  u'last_order_date': u'2017-05-08T05:55:46Z',
  u'last_order_id': 38,
  u'last_update': u'2017-05-08T05:55:46Z',
  u'orders_count': 7,
  u'role': u'administrator',
  u'shipping_address': {u'address_1': u'Jogeshvari',
   u'address_2': u'',
   u'city': u'mumbai',
   u'company': u'',
   u'country': u'IN',
   u'first_name': u'jinal',
   u'last_name': u'patel',
   u'postcode': u'400068',
   u'state': u'MH'},
  u'total_spent': u'2830.00',
  u'username': u'admin'},
 u'customer_id': 1,
 u'customer_ip': u'114.143.66.177',
 u'customer_user_agent': u'mozilla/5.0 (x11; ubuntu; linux x86_64; rv:47.0) gecko/20100101 firefox/47.0',
 u'fee_lines': [],
 u'id': 31,
 u'line_items': [{u'id': 4,
   u'meta': [],
   u'name': u'Test Product',
   u'price': u'1800.00',
   u'product_id': 11,
   u'quantity': 6,
   u'sku': u'TSTPRD',
   u'subtotal': u'10800.00',
   u'subtotal_tax': u'0.00',
   u'tax_class': u'',
   u'total': u'10800.00',
   u'total_tax': u'0.00'}],
 u'note': u'',
 u'order_key': u'wc_order_590c7dc3a74ea',
 u'order_number': u'31',
 u'payment_details': {u'method_id': u'cheque',
  u'method_title': u'Check payments',
  u'paid': False},
 u'shipping_address': {u'address_1': u'Jogeshvari',
  u'address_2': u'',
  u'city': u'mumbai',
  u'company': u'',
  u'country': u'IN',
  u'first_name': u'jinal',
  u'last_name': u'patel',
  u'postcode': u'400068',
  u'state': u'MH'},
 u'shipping_lines': [{u'id': 5,
   u'method_id': u'flat_rate:3',
   u'method_title': u'Flat rate',
   u'total': u'200.00'}],
 u'shipping_methods': u'Flat rate',
 u'shipping_tax': u'0.00',
 u'status': u'cancelled',
 u'subtotal': u'10800.00',
 u'tax_lines': [],
 u'total': u'11000.00',
 u'total_discount': u'0.00',
 u'total_line_items_quantity': 6,
 u'total_shipping': u'200.00',
 u'total_tax': u'0.00',
 u'updated_at': u'2017-05-09T13:55:26Z',
 u'view_order_url': u'http://woocomm.globalteckz.com/my-account/view-order/31'}

