
{u'attributes': [],
 u'average_rating': u'0.00',
 u'backordered': False,
 u'backorders_allowed': False,
 u'button_text': u'',
 u'catalog_visibility': u'visible',
 u'categories': [u'Dress', u'Root', u'Women'],
 u'created_at': u'2017-04-20T11:09:29Z',
 u'cross_sell_ids': [],
 u'description': u'<p>Test Product</p>\n',
 u'dimensions': {u'height': u'20',
  u'length': u'20',
  u'unit': u'in',
  u'width': u'20'},
 u'download_expiry': -1,
 u'download_limit': -1,
 u'download_type': u'standard',
 u'downloadable': False,
 u'downloads': [],
 u'featured': False,
 u'featured_src': u'http://woocomm.globalteckz.com/wp-content/uploads/2017/04/Nippon_Paper_Industries_company_logo.png',
 u'grouped_products': [],
 u'id': 11,
 u'images': [{u'alt': u'',
   u'created_at': u'2017-04-20T11:08:36Z',
   u'id': 12,
   u'position': 0,
   u'src': u'http://woocomm.globalteckz.com/wp-content/uploads/2017/04/Nippon_Paper_Industries_company_logo.png',
   u'title': u'Nippon_Paper_Industries_company_logo',
   u'updated_at': u'2017-04-20T11:08:36Z'}],
 u'in_stock': True,
 u'managing_stock': True,
 u'menu_order': 0,
 u'on_sale': True,
 u'parent': [],
 u'parent_id': 0,
 u'permalink': u'http://woocomm.globalteckz.com/product/test-product/',
 u'price': u'1800',
 u'price_html': u'<del><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#36;</span>2,000.00</span></del> <ins><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#36;</span>1,800.00</span></ins>',
 u'product_url': u'',
 u'purchase_note': u'',
 u'purchaseable': True,
 u'rating_count': 0,
 u'regular_price': u'2000',
 u'related_ids': [15],
 u'reviews_allowed': True,
 u'sale_price': u'1800',
 u'shipping_class': u'',
 u'shipping_class_id': None,
 u'shipping_required': True,
 u'shipping_taxable': True,
 u'short_description': u'<p>Test Product</p>\n',
 u'sku': u'TSTPRD',
 u'sold_individually': False,
 u'status': u'publish',
 u'stock_quantity': 199,
 u'tags': [],
 u'tax_class': u'',
 u'tax_status': u'taxable',
 u'taxable': False,
 u'title': u'Test Product',
 u'total_sales': 1,
 u'type': u'simple',
 u'updated_at': u'2017-04-20T11:09:29Z',
 u'upsell_ids': [],
 u'variations': [],
 u'virtual': False,
 u'visible': True,
 u'weight': u'300'}