{u'billing_address': {u'address_1': u'jogeshwari',
  u'address_2': u'jogeshwari',
  u'city': u'Mumbai',
  u'company': u'Globalteckz',
  u'country': u'IN',
  u'email': u'krishna@globalteckz.com',
  u'first_name': u'krishna',
  u'last_name': u'yadav',
  u'phone': u'567868798789',
  u'postcode': u'400068',
  u'state': u'MH'},
 u'cart_tax': u'0.00',
 u'completed_at': u'1970-01-01T00:00:00Z',
 u'coupon_lines': [],
 u'created_at': u'2017-05-10T11:40:00Z',
 u'currency': u'USD',
 u'customer': {u'avatar_url': u'http://1.gravatar.com/avatar/72936ae15aba9c6f5261e06894ad6746?s=96',
  u'billing_address': {u'address_1': u'jogeshwari',
   u'address_2': u'jogeshwari',
   u'city': u'Mumbai',
   u'company': u'Globalteckz',
   u'country': u'IN',
   u'email': u'krishna@globalteckz.com',
   u'first_name': u'krishna',
   u'last_name': u'yadav',
   u'phone': u'567868798789',
   u'postcode': u'400068',
   u'state': u'MH'},
  u'created_at': u'2017-05-04T14:04:28Z',
  u'email': u'krishna@globalteckz.com',
  u'first_name': u'krishna',
  u'id': 2,
  u'last_name': u'yadav',
  u'last_order_date': u'2017-05-10T11:40:00Z',
  u'last_order_id': 43,
  u'last_update': u'2017-05-04T14:22:10Z',
  u'orders_count': 1,
  u'role': u'customer',
  u'shipping_address': {u'address_1': u'Kandivali',
   u'address_2': u'Kandivali',
   u'city': u'mumbai',
   u'company': u'Globalteckz',
   u'country': u'IN',
   u'first_name': u'krishna',
   u'last_name': u'yadav',
   u'postcode': u'400067',
   u'state': u'MH'},
  u'total_spent': u'0.00',
  u'username': u'krishna@globalteckz.com'},
 u'customer_id': 2,
 u'customer_ip': u'',
 u'customer_user_agent': u'',
 u'fee_lines': [],
 u'id': 43,
 u'line_items': [{u'id': 16,
   u'meta': [],
   u'name': u'T-Shirt - Red',
   u'price': u'10.00',
   u'product_id': 21,
   u'quantity': 1,
   u'sku': u'RED',
   u'subtotal': u'10.00',
   u'subtotal_tax': u'0.00',
   u'tax_class': u'',
   u'total': u'10.00',
   u'total_tax': u'0.00'},
  {u'id': 17,
   u'meta': [],
   u'name': u'T-Shirt - Black',
   u'price': u'50.00',
   u'product_id': 22,
   u'quantity': 1,
   u'sku': u'BLACK',
   u'subtotal': u'50.00',
   u'subtotal_tax': u'0.00',
   u'tax_class': u'',
   u'total': u'50.00',
   u'total_tax': u'0.00'},
  {u'id': 18,
   u'meta': [],
   u'name': u'T-Shirt - Blue',
   u'price': u'180.00',
   u'product_id': 23,
   u'quantity': 1,
   u'sku': u'Blue',
   u'subtotal': u'180.00',
   u'subtotal_tax': u'0.00',
   u'tax_class': u'',
   u'total': u'180.00',
   u'total_tax': u'0.00'}],
 u'note': u'',
 u'order_key': u'wc_order_5912fcec339df',
 u'order_number': u'43',
 u'payment_details': {u'method_id': u'cheque',
  u'method_title': u'Check payments',
  u'paid': False},
 u'shipping_address': {u'address_1': u'Kandivali',
  u'address_2': u'Kandivali',
  u'city': u'mumbai',
  u'company': u'Globalteckz',
  u'country': u'IN',
  u'first_name': u'krishna',
  u'last_name': u'yadav',
  u'postcode': u'400067',
  u'state': u'MH'},
 u'shipping_lines': [],
 u'shipping_methods': u'',
 u'shipping_tax': u'0.00',
 u'status': u'pending',
 u'subtotal': u'240.00',
 u'tax_lines': [],
 u'total': u'240.00',
 u'total_discount': u'0.00',
 u'total_line_items_quantity': 3,
 u'total_shipping': u'0.00',
 u'total_tax': u'0.00',
 u'updated_at': u'2017-05-10T11:43:40Z',
 u'view_order_url': u'http://woocomm.globalteckz.com/my-account/view-order/43'}
